name: parser

services:

  backend:
    build: ./backend
    ports:
      - "1337:1337"
    depends_on:
      - psql
    volumes:
      - ./backend/run:/home/app/run

  frontend:
    build: ./frontend
    ports:
      - "1338:1338"
    environment:
      PORT: 1338

  psql:
    image: postgres:latest

    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: "postgres"
