openapi: 3.0.0
info:
  title: Template project docs
  version: 1
servers:
  - url: http://localhost:1337
    description: Local development server
paths:
  /vacancies:
    get:
      summary: Get head hunter
      parameters:
        - in: query
          name: offset
          schema:
            type: "integer"
            format: INT64
          required: true
        - in: query
          name: limit
          schema:
            type: "integer"
            format: INT32
          required: true
        - in: query
          name: query
          schema:
            type: "string"
          required: true
        - in: query
          name: area
          schema:
            type: "string"
          required: true
        - in: query
          name: salary
          schema:
            type: "integer"
            format: INT32
          required: true
        - in: query
          name: order_by
          schema:
            type: "string"
          required: true
      responses: {}
components:
  securitySchemes:
    template:
      type: "http"
      scheme: bearer
